### ISSUE TITLE
Crawl data for Product and Shop

### ISSUE THREAD

**Issue by thanhdt21** [longtrinh1749/ShopeeFoodClone#16]

**Comment by MS1908** [comment]
Data crawled from Shopee Food
[category.csv](https://github.com/longtrinh1749/ShopeeFoodClone/files/7457242/category.csv)
[food.csv](https://github.com/longtrinh1749/ShopeeFoodClone/files/7457243/food.csv)
[restaurant.csv](https://github.com/longtrinh1749/ShopeeFoodClone/files/7457244/restaurant.csv)

**Comment by MS1908** [comment]
Data crawled from Shopee Food
[category.csv](https://github.com/longtrinh1749/ShopeeFoodClone/files/7457273/category.csv)
[food.csv](https://github.com/longtrinh1749/ShopeeFoodClone/files/7457274/food.csv)
[restaurant.csv](https://github.com/longtrinh1749/ShopeeFoodClone/files/7457275/restaurant.csv)
